# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/principal_component_analysis
owner: devteam
name: principal_component_analysis
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
