# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/compute_motifs_frequency
owner: devteam
name: compute_motifs_frequency
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
