# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastx_barcode_splitter
owner: devteam
name: fastx_barcode_splitter
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
