# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/suite_fastx_toolkit_0_0_13
owner: devteam
name: suite_fastx_toolkit_0_0_13
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
