# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/samtools_bedcov
owner: devteam
name: samtools_bedcov
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
