# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_freebayes_0_9_6_9608597d
owner: devteam
name: package_freebayes_0_9_6_9608597d
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
