# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/compute_motif_frequencies_for_all_motifs
owner: devteam
name: compute_motif_frequencies_for_all_motifs
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
