# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/suite_gatk_1_4
owner: devteam
name: suite_gatk_1_4
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
