# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/data_manager_bwa_index_builder
owner: devteam
name: data_manager_bwa_index_builder
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
