# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/mutate_snp_codon
owner: devteam
name: mutate_snp_codon
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
