# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_inputproto_2_2
owner: devteam
name: package_inputproto_2_2
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
