# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastq_to_fasta
owner: devteam
name: fastq_to_fasta
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
