# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/subtract_query
owner: devteam
name: subtract_query
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
