# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/suite_bamtools_2_3_0
owner: devteam
name: suite_bamtools_2_3_0
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
