# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/logistic_regression_vif
owner: devteam
name: logistic_regression_vif
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
