# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/variants_validate
owner: devteam
name: variants_validate
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
