# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastx_artifacts_filter
owner: devteam
name: fastx_artifacts_filter
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
