# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/getindels_2way
owner: devteam
name: getindels_2way
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
