# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/convert_solid_color2nuc
owner: devteam
name: convert_solid_color2nuc
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
