# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/short_reads_figure_score
owner: devteam
name: short_reads_figure_score
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
