# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_libxcb_1_9_1
owner: devteam
name: package_libxcb_1_9_1
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
