# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_libgtextutils_0_6
owner: devteam
name: package_libgtextutils_0_6
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
