# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fasta_to_tabular
owner: devteam
name: fasta_to_tabular
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
