# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/variant_recalibrator
owner: devteam
name: variant_recalibrator
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
