# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/vcfselectsamples
owner: devteam
name: vcfselectsamples
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
