# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/megablast_xml_parser
owner: devteam
name: megablast_xml_parser
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
