# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_bwa_0_7_10_039ea20639
owner: devteam
name: package_bwa_0_7_10_039ea20639
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
