# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/pileup_interval
owner: devteam
name: pileup_interval
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
