# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_libxtrans_1_2_7
owner: devteam
name: package_libxtrans_1_2_7
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
