# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/linear_regression
owner: devteam
name: linear_regression
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
