# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/vcftools_merge
owner: devteam
name: vcftools_merge
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
