# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_bioc_hilbertvis_1_18_0
owner: devteam
name: package_bioc_hilbertvis_1_18_0
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
