# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_bx_python_0_7
owner: devteam
name: package_bx_python_0_7
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
