# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_clustalw_2_1
owner: devteam
name: package_clustalw_2_1
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
