# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/emboss_datatypes
owner: devteam
name: emboss_datatypes
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
