# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/unified_genotyper
owner: devteam
name: unified_genotyper
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
