# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastx_reverse_complement
owner: devteam
name: fastx_reverse_complement
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
