# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_galaxy_ops_1_0_0
owner: devteam
name: package_galaxy_ops_1_0_0
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
