# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/varscan_version_2
owner: devteam
name: varscan_version_2
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
