# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastq_masker_by_quality
owner: devteam
name: fastq_masker_by_quality
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
