# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/dwt_var_perfeature
owner: devteam
name: dwt_var_perfeature
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
