# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/canonical_correlation_analysis
owner: devteam
name: canonical_correlation_analysis
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
