# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_ccat_3_0
owner: devteam
name: package_ccat_3_0
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
