# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/samtools_slice_bam
owner: devteam
name: samtools_slice_bam
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
