# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_express_1_1_1
owner: devteam
name: package_express_1_1_1
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
