# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/samtools_stats
owner: devteam
name: samtools_stats
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
