# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_libpng_1_6_7
owner: devteam
name: package_libpng_1_6_7
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
