# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastq_paired_end_joiner
owner: devteam
name: fastq_paired_end_joiner
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
