# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/microsats_mutability
owner: devteam
name: microsats_mutability
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
