# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/samtools_phase
owner: devteam
name: samtools_phase
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
