# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/tophat_fusion_post
owner: devteam
name: tophat_fusion_post
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
