# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/variant_apply_recalibration
owner: devteam
name: variant_apply_recalibration
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
