# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/vcftools_compare
owner: devteam
name: vcftools_compare
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
