# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fasta_formatter
owner: devteam
name: fasta_formatter
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
