# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/samtools_reheader
owner: devteam
name: samtools_reheader
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
