# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/filter_transcripts_via_tracking
owner: devteam
name: filter_transcripts_via_tracking
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
