# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/delete_overlapping_indels
owner: devteam
name: delete_overlapping_indels
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
