# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/annotation_profiler
owner: devteam
name: annotation_profiler
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
