# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/samtools_mpileup
owner: devteam
name: samtools_mpileup
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
