# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fasta_concatenate_by_species
owner: devteam
name: fasta_concatenate_by_species
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
