# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/dwt_cor_avb_all
owner: devteam
name: dwt_cor_avb_all
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
