# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastq_quality_converter
owner: devteam
name: fastq_quality_converter
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
