# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/vcfrandomsample
owner: devteam
name: vcfrandomsample
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
