# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_bowtie_2_2_4
owner: devteam
name: package_bowtie_2_2_4
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
