# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_fastqc_0_10_1
owner: devteam
name: package_fastqc_0_10_1
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
