# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_libxproto_7_0_23
owner: devteam
name: package_libxproto_7_0_23
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
