# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_rmap_2_05
owner: devteam
name: package_rmap_2_05
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
