# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/suite_samtools_1_2
owner: devteam
name: suite_samtools_1_2
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
