# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_bamtools_2_3_0_2d7685d2ae
owner: devteam
name: package_bamtools_2_3_0_2d7685d2ae
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
