# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/split_paired_reads
owner: devteam
name: split_paired_reads
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
