# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/suite_gops_1_0
owner: devteam
name: suite_gops_1_0
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
