# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_ghostscript_9_10
owner: devteam
name: package_ghostscript_9_10
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
