# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_freebayes_0_9_14_8a407cf5f4
owner: devteam
name: package_freebayes_0_9_14_8a407cf5f4
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
