# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/tables_arithmetic_operations
owner: devteam
name: tables_arithmetic_operations
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
