# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/categorize_elements_satisfying_criteria
owner: devteam
name: categorize_elements_satisfying_criteria
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
