# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/tabular_to_fastq
owner: devteam
name: tabular_to_fastq
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
