# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_libxcb_proto_1_8
owner: devteam
name: package_libxcb_proto_1_8
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
