# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/bowtie_wrappers
owner: devteam
name: bowtie_wrappers
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
