# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/generate_pc_lda_matrix
owner: devteam
name: generate_pc_lda_matrix
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
