# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/fastx_quality_statistics
owner: devteam
name: fastx_quality_statistics
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
