# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_libxslt_1_1_28
owner: devteam
name: package_libxslt_1_1_28
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
