# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_vcftools_0_1_11
owner: devteam
name: package_vcftools_0_1_11
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
