# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_weblogo_3_3
owner: devteam
name: package_weblogo_3_3
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
