# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/variant_combine
owner: devteam
name: variant_combine
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
