# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/analyze_covariates
owner: devteam
name: analyze_covariates
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
