# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/short_reads_trim_seq
owner: devteam
name: short_reads_trim_seq
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
