owner: devteam
name: data_manager_twobit_builder
categories:
- Data Managers
description: Twobit data manager.
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/data_managers/data_manager_twobit_builder
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
