# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/getindelrates_3way
owner: devteam
name: getindelrates_3way
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
