# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/show_beginning
owner: devteam
name: show_beginning
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
