# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/count_gff_features
owner: devteam
name: count_gff_features
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
