# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_xorg_macros_1_17_1
owner: devteam
name: package_xorg_macros_1_17_1
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
