# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_blast_plus_2_2_26
owner: devteam
name: package_blast_plus_2_2_26
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
