# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/sam_bitwise_flag_filter
owner: devteam
name: sam_bitwise_flag_filter
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
