# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/package_freebayes_0_9_18_0059bdf
owner: devteam
name: package_freebayes_0_9_18_0059bdf
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
