# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/compute_q_values
owner: devteam
name: compute_q_values
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
