# repository published to https://toolshed.g2.bx.psu.edu/repos/devteam/maf_cpg_filter
owner: devteam
name: maf_cpg_filter
description: description
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
